### ISSUE TITLE
python service won't start

### ISSUE THREAD

**Issue by eglaw** [wodby/docker4python#1]
`/etc/init.d/gunicorn: line 9: gunicorn: command not found`

Git clone from this repo.
`$ make up` - starts everything, BUT... the python image dies.
it gives error and exit code 127 on container, domino effect => nginx service falls down as well, as it relies on python with exit code 1.

Debugged around a little:
i've tried building the python image alone and starting it .. it builds cleanly, but it's not starting. As far as it inherits the wodby/python image (3.7-dev-macos-0.4.2) i've read it's Dockerfile and the part where it copies the **gunicorn.init.d** inside `/etc/init.d` is ok, the script is there in project image too, but the part where inside /etc/init.d/gunicorn line:9 tries to start the gunicorn itself, the image exits with error. There's no such executable as gunicorn.

Firstly i've found that my personal requirements.txt must be in project root with (for example Django, gunicorn, psycopg2, etc...) at least present. Everything is ok so far, during the build phase i see the gunicorn being installed with pip in `/usr/src/app/.local/bin/gunicorn` (why it's installed here and not in some kind of widely used /usr/local/bin?? 'cuz of alpine?)
but later during the launching phase the container can't find the executable. [$PATH problems for the wodby user ???]

Just as is ... with **PYTHON_TAG=3.7-dev-macos-0.4.2** and 

**requirements.txt** in projects' root
```
gunicorn
psycopg2
Django
django-redis
```
try `docker-compose up` with no detached (not the `$ make up` that starts with -d)
you'll see the python image falls with 127 code, and nginx with code 1.
 
### Host OS 
macOS Mojave 10.14.5

### Docker info output
```
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 3.855GiB
Name: linuxkit-025000000001
ID: UZ6N:Q3KL:KYR5:WX7G:Q6X6:RE3I:M7PE:BJOV:K4DV:ERYV:3KRO:NK2P
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 24
 Goroutines: 50
 System Time: 2019-07-26T11:04:01.20611512Z
 EventsListeners: 2
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

**Comment by csandanov** [comment]
You're right, the location should've been different otherwise installed packages overridden by the bind mount. I've released `wodby/python` image update, packages location is now `/home/wodby/.local`. Also, please note that the default `Dockerfile` assumes your application name is `myapp` otherwise it will also fail to start up.

**Comment by eglaw** [comment]
> You're right, the location should've been different otherwise installed packages overridden by the bind mount. I've released `wodby/python` image update, packages location is now `/home/wodby/.local`. Also, please note that the default `Dockerfile` assumes your application name is `myapp` otherwise it will also fail to start up.

I'll prefer to override the .initd script where gunicorn command will call myCustomName application instead.

**Comment by csandanov** [comment]
it's also possible to change the app name via the env var in dockerfile

**Comment by eglaw** [comment]
I've tested.
Now everything works - Thx @csandanov!
